version: '3.8'

services:

  database:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pcmirea_db:/var/lib/postgresql/data
    restart:
      always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 3

  backend:
    build: ./server/
    environment:
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: database
      DB_PORT: 5432
    depends_on:
      database:
        condition: service_healthy

  nginx:
    image: nginx:1.25.5
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./html:/usr/share/nginx/html:ro
    depends_on:
      database:
        condition: service_healthy
      backend:
        condition: service_started

  # Dev Only
  adminer:
    image: adminer:4.8.1
    ports:
      - 9090:8080

volumes:
  pcmirea_db: